version: 1.0.{build}
configuration: Release
platform: Any CPU

environment:
  AssemblyFilePath: '*\*\AssemblyInfo.cs'
  
  #If true then all 3 variables starting with "Private_Nuget*" have to be defined.
  Is_Uploading_Nuget_To_Private_Server: True
    #URL where Nuget can download private dependencies from.
  Private_Nuget_Server_Repo_URL:
    secure: XXXXXX
    #URL where Nuget can upload to.
  Private_Nuget_Server_URL:
    secure: XXXXXX
    #API Key for Private server.
  Private_Nuget_API_Key:
    secure: XXXXXX

  #If True then Public_Nuget_API_Key has to be defined.
  Is_Uploading_Nuget_To_Public_Serever: False
    #API Key for https://www.nuget.org/ server
  Public_Nuget_API_Key:
    secure: XXXXXX

before_build:
- ps: .\Scripts\before_build.ps1

build:
  project: PojectName.sln
  verbosity: normal

after_build:
- ps: .\Scripts\after_build.ps1
    

artifacts:
- path: '*.nupkg'
  name: Package
  
deploy_script:
- ps:  .\Scripts\deploy_script.ps1 