version: 1.0.{build}
configuration: Release
platform: Any CPU

environment:
  Private_Nuget_Server_Repo_URL:
    secure: XXXXXX
  Private_Nuget_Server_URL:
    secure: XXXXXX
  Private_Nuget_API_Key:
    secure: XXXXXX

before_build:
- ps: .\Scripts\before_build.ps1

build:
  project: PojectName.sln
  verbosity: normal

after_build:
- ps: .\Scripts\after_build.ps1
    

artifacts:
- path: '*.nupkg'
  name: Package
  
deploy_script:
- ps: nuget push *.nupkg -s $env:Private_Nuget_Server_URL $env:Private_Nuget_API_Key